### ISSUE TITLE
Error: The key pair 'arn:aws:ec2:<region>:<account_id>:keypair/CustomKeyPair' does not exist

### ISSUE THREAD

**Issue by cayblood** [binxio/cfn-secret-provider#12]
I've added these resources to a cloudformation template and the keypair is successfully created. The same keypair is a dependency of the instance I'm trying to create and is referenced by it like so:

```
  KeyPair:
    Type: Custom::KeyPair
    DependsOn:
      - CFNSecretProvider
      - PrivateKey
    Properties:
      Name: CustomKeyPair
      PublicKeyMaterial: !GetAtt
        - PrivateKey
        - PublicKey
      ServiceToken: !Join
        - ":"
        - - arn:aws:lambda
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - !Ref CFNSecretProvider

...

  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
     - CertBucket
     - KeyPair
     - InstanceProfile
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [AWSRegionToAMI, !Ref "AWS::Region", AMI]
      KeyName: !Ref KeyPair
      ...
```
However, when the instance is created, I get an error saying the key pair doesn't exist. Looking in the event log, the keypair is successfully created, and I can see it in the EC2 console. Any idea what the issue is?
