### ISSUE TITLE
CFN is returning SSMPutParameter Access denied

### ISSUE THREAD

**Issue by vennemp** [binxio/cfn-secret-provider#28]
I am running your CFN to create the key pair generating lambda function.  I have made no edits to your code but I am getting an error.

Failed to create resource. An error occurred (AccessDeniedException) when calling the PutParameter operation: User: arn:aws:sts::xxxxxxxxxx:assumed-role/Research3-LambdaRole-87IICXNLGUL3/binxio-cfn-secret-provider is not authorized to perform: ssm:PutParameter on resource: arn:aws:ssm:us-east-1:xxxxxxxxx:parameter/app/Research3/demo/private-key

**Comment by mvanholsteijn** [comment]
Hi @vennemp, I suspect that you did not deploy using the [cfn-resource-provider.yaml](https://github.com/binxio/cfn-secret-provider/blob/master/cloudformation/cfn-resource-provider.yaml) template. At [line 25](https://github.com/binxio/cfn-secret-provider/blob/master/cloudformation/cfn-resource-provider.yaml#L25 ) it is granted the ssm:PutParameter action. Can you check the permissions associated with your lambda?

**Comment by vennemp** [comment]
I took the code and copied it into another template.  It is creating the actual function.  Just failing when it makes the call to create the private key.

These are the permissions associated with the lambda

```yaml
LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties:
      PolicyName: CFNCustomSecretProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - iam:CreateAccessKey
              - iam:DeleteAccessKey
              - iam:UpdateAccessKey
              - ssm:PutParameter
              - ssm:GetParameter
              - ssm:DeleteParameter
              - ec2:ImportKeyPair
              - ec2:DeleteKeyPair
              - secretsmanager:DeleteSecret
              - secretsmanager:CreateSecret
              - secretsmanager:UpdateSecret
            Effect: Allow
            Resource:
              - '*'
          - Action:
              - kms:Decrypt
            Effect: Allow
            Resource:
              - !GetAtt 'Key.Arn'
          - Action:
              - logs:*
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Ref 'LambdaRole'
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
```
