### ISSUE TITLE
Broken v1.0.0

### ISSUE THREAD

**Issue by dalibor-aleksic-atomia** [binxio/cfn-secret-provider#29]
Stack stucks in `CREATE_IN_PROGRESS` state

```
AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Test Stack
Resources:
  DBPassword:
    Type: Custom::Secret
    Properties:
      Name: /test/DBPassword/PGPASSWORD
      KeyAlias: alias/aws/ssm
      Alphabet: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
      Length: 30
      ReturnSecret: true
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-secret-provider'
```
Checked CloudWatch logs for lamba function and found error log:

```
Runtime.HandlerNotFound: Handler 'handler' missing on module 'secrets'
```

Deployed v0.13.3 and everything went smooth
