### ISSUE TITLE
Error : "Handler 'handler' missing on module 'secrets'" when deployed from zip

### ISSUE THREAD

**Issue by kzhou57** [binxio/cfn-secret-provider#59]
I have tried both 1.4.4 and 2.0.1 zip file 

My cloudformation looks like following: 

```
  CFNSecretProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
    Properties:
      Description: CloudFormation Custom:Secret implementation
      Code:
        S3Bucket: !Sub '${LambdaS3Bucket}'
        S3Key: !Sub '${LambdaS3Path}/cfn-secret-provider-2.0.1.zip'
      FunctionName: 'binxio-cfn-secret-provider'
      Handler: secrets.handler
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.9

```
